# Generated by Django 3.0.8 on 2020-12-16 11:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('available', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
